---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deamon
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mydaemonpod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcustom
          image: coolgourav147/nginx-custom:v1
          imagePullPolicy: Never
