apiVersion: v1
kind: ReplicationController
metadata:
  name: firstrc
  labels:
    appname: voatingapp
spec:
  replicas: 1
  template:
    metadata:
      name: myfirstpod
      labels:
        type: app
    spec:
      containers:
        - name: nginxcusto
          image: coolgourav147/nginx-custom:v2