---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: testvolume
           
  volumes:
    - name: testvolume
      hostPath:
        path: /tmp/mydata 