---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeploy
  labels:
    name: firstdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcustom
          image: coolgourav147/nginx-custom:v1
          imagePullPolicy: Never
      nodeSelector:
        size: "large"
