apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firstrs
  labels:
    appname: voatingapp
spec:
  replicas: 3
  selector:

  template:
    metadata:
      name: mypod
      labels:
        app: myapp

    spec:
      containers:
        - name: nginxcusto
          image: coolgourav147/nginx-custom