apiVersion: v1
kind: Pod
metadata:
  name: secretvol
spec:
  containers:
    - name: nginxcusto
      image: coolgourav147/nginx-custom:v1
      imagePullPolicy: Never
      volumeMounts:
       - mountPath: /secret
         name: secvol  
  volumes:
    - name: secvol
      secret:
         secretName: mysecret