apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    name: firstdeploy
  annotations:
    kubernetes.io/change-cause: "Now roll down to version v1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcusto
          image: coolgourav147/nginx-custom:v1
          imagePullPolicy: Never